project:
  type: website

website:
  favicon: images/favicon/favicon_fullres.png
  navbar:
    title: false
    logo: images/logo/logo.png
    logo-alt: "The Openscapes logo -- orange text that reads 'openscapes' sitting above small berry 'data points'"
    right:
      - href: index.qmd
        text: "HOME"
      - href: about.qmd
        text: "ABOUT"
        menu:
          - text: "MEDIA"
            href: media.qmd
      - href: initiatives.qmd
        text: "INITIATIVES"
        menu:
         - text: "CHAMPIONS PROGRAM"
           href: champions-program.qmd
      - href: blog.qmd
        text: "BLOG"
      - href: connect.qmd
        text: "CONNECT"
      - icon: github
        href: https://github.com/openscapes
      - icon: twitter
        href: https://twitter.com/openscapes
      - icon: envelope
        href: mailto:hello@openscapes.org
  page-footer:    
    background: light
    left: Openscapes is licensed under a [Creative Commons Attributions 4.0 International License](https://creativecommons.org/licenses/by/4.0/)
    right: This website is built with ❤️ and [Quarto](https://quarto.org/)
      
format:
  html:
    page-layout: full
    theme: 
      - styles.scss
    mainfont: Sen
    toc: true



