project:
  type: website

website:
  favicon: images/favicon/favicon_fullres.png
  navbar:
    title: false
    logo: images/logo/openscapes_hex_badge.png 
    logo-alt: "A stylized landscape showing rolling hills in different shades of orange, with purple flowers along the ridgelines. Subtle gridlines on the hills and circle packing in the flowers give a nod to data in the environment."
    right:
      - text: "HOME"
        href: index.qmd
      - text: "ABOUT"
        menu:
          - text: "ABOUT US"
            href: about.qmd
          - text: "OUR APPROACH"
            href: approach.qmd
          - text: "OUR TEAM" # Do we need this as separate navbar item or is ABOUT US enough?
            href: team.qmd
          - text: "MEDIA"
            href: media.qmd
          - text: "STORIES"
            href: stories.qmd 
          - text: "CODE OF CONDUCT"
            href: code_of_conduct.qmd # Let's change these all to - instead of _
      - text: "INITIATIVES"
        href: initiatives.qmd
        # menu:
        #  - text: "CHAMPIONS PROGRAM"
        #    href: champions_program.qmd
        #  - text: "MENTORS FRAMEWORK"
        #    href: mentors_framework.qmd
        #  - text: "REFLECTIONS PROGRAM"
        #    href: reflections_program.qmd
        #  - text: "PATHWAYS TO OPEN SCIENCE PROGRAM"
        #    href: pathways_to_open_science_program.qmd
      - text: "BLOG"
        href: blog.qmd
      - text: "CONNECT"
        href: connect.qmd # TODO maybe rename url
          #- text: "OUR EVENTS"
           # href: events.qmd
 #         - text: "FIND LEARNING RESOURCES" TODO: review & move to Champions series
 #            href: resources.qmd
      - icon: github
        href: https://github.com/openscapes
      - icon: twitter
        href: https://twitter.com/openscapes
      - icon: mastodon
        href: https://fosstodon.org/@openscapes
      - icon: envelope
        href: mailto:hello@openscapes.org
  
  page-footer:    
    background: light
    left: Openscapes is licensed under a [Creative Commons Attributions 4.0 International License](https://creativecommons.org/licenses/by/4.0/)
    right: This website is built with {{< fa heart title="a heart" >}} and [Quarto](https://quarto.org/)
      
format:
  html:
    page-layout: full
    theme: 
      - styles.scss
    mainfont: Sen




