project:
  type: website

website:
  favicon: images/favicon/favicon_fullres.png
  navbar:
    title: false
    logo: images/logo/openscapes_hex_badge.png 
    logo-alt: "A stylized landscape showing rolling hills in different shades of orange, with purple flowers along the ridgelines. Subtle gridlines on the hills and circle packing in the flowers give a nod to data in the environment."
    right:
      - text: "HOME"
        href: index.qmd
      - text: "ABOUT"
        menu:
          - text: "WHO ARE WE?"
            href: who_are_we.qmd
          - text: "OUR APPROACH"
            href: approach.qmd
          - text: "MEDIA"
            href: media.qmd
          - text: "OUR TEAM"
            href: team.qmd
          - text: "CODE OF CONDUCT"
            href: code_of_conduct.qmd
      - text: "INITIATIVES"
        menu:
         - text: "CHAMPIONS PROGRAM"
           href: champions_program.qmd
         - text: "REFLECTIONS PROGRAM"
           href: reflections_program.qmd
         - text: "PATHWAYS TO OPEN SCIENCE PROGRAM"
           href: pathways_to_open_science_program.qmd
         - text: "MENTORS FRAMEWORK"
           href: mentors_framework.qmd
      - text: "BLOG"
        href: blog.qmd
      - text: "GET INVOLVED"
        menu: 
          - text: "CONNECT WITH US"
            href: connect.qmd
          - text: "ATTEND AN EVENT"
            href: events.qmd
          - text: "FIND LEARNING RESOURCES"
            href: resources.qmd
      - icon: github
        href: https://github.com/openscapes
      - icon: twitter
        href: https://twitter.com/openscapes
      - icon: envelope
        href: mailto:hello@openscapes.org
  page-footer:    
    background: light
    left: Openscapes is licensed under a [Creative Commons Attributions 4.0 International License](https://creativecommons.org/licenses/by/4.0/)
    right: This website is built with {{< fa heart title="a heart" >}} and [Quarto](https://quarto.org/)
      
format:
  html:
    page-layout: full
    theme: 
      - styles.scss
    mainfont: Sen




